### ISSUE TITLE
变量问题

### ISSUE THREAD

**Issue by lxmicode** [YouHolmes/JdScripts#3]
请教下，在Linux node环境跑，
是否能有类似github action 环境有一个全局的变量，或者说一个新配置文件，存放配置，
如cookie存放位置，而不是直接修改jdcookie.Js里面。
因为放里面有时候JS更新冲突的时候，无法自动同步代码，如果能像action那样单独开来，比较方便

**Comment by YouHolmes** [comment]
纯node跑没有环境变量或配置文件用来配置，docker、云函数有实现
