### ISSUE TITLE
信息通知plus+接口更新下

### ISSUE THREAD

**Issue by lxmicode** [YouHolmes/JdScripts#6]
老  url: `http://www.pushplus.plus/send`,
  新   url: `http://pushplus.hxtrip.com/send`,

**Comment by lxmicode** [comment]
京东变动好像也没提醒，求更新

**Comment by YouHolmes** [comment]
本人一直也是用的pushplus，推送没有问题，检查一下 PUSH_PLUS_TOKEN 配置没有
两个网址都用过，还是现用的推送消息展示框看着舒服

**Comment by YouHolmes** [comment]
pushplus.plus 才是升级版

**Comment by lxmicode** [comment]
好吧，找到版本了，难怪PUSH_PLUS_TOKEN 一直没用
