### ISSUE TITLE
更新代码地址改成git后报错连接不到端口22 怎么解决呢

### ISSUE THREAD

**Issue by zsewqsc2008** [YouHolmes/JdScripts#9]
以下是程序运行起来后的报错

设定远程仓库地址...
HEAD is now at 6670c389 新的女装盲盒
git pull拉取最新代码...
ssh: connect to host github.com port 22: Connection refused

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by zsewqsc2008** [comment]
使用docker exec -it jd_scripts /bin/sh，进入容器后 用git会这样，在外边直接用git clone  是正常的

**Comment by YouHolmes** [comment]
应该跟容器没关系
